name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, mysql, zip
          coverage: xdebug
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install Composer dependencies
        run: |
          composer config platform.php ${{ matrix.php-version }}
          composer update --prefer-dist --no-progress --no-interaction --prefer-stable

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        if: matrix.php-version == '8.0'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: |
          composer config platform.php 7.4
          composer update --prefer-dist --no-progress --no-interaction --prefer-stable

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=vendor/,node_modules/,tests/,temp/ .
        continue-on-error: true

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
        continue-on-error: true

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create plugin archive
        run: |
          mkdir -p build
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='tests' \
            --exclude='vendor' \
            --exclude='node_modules' \
            --exclude='*.log' \
            --exclude='.env*' \
            --exclude='composer.*' \
            --exclude='phpunit.xml*' \
            --exclude='phpstan.*' \
            --exclude='.*' \
            --exclude='temp/' \
            . build/gf-verifytx-addon/
          cd build
          zip -r gf-verifytx-addon.zip gf-verifytx-addon/

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: gf-verifytx-addon-${{ github.sha }}
          path: build/gf-verifytx-addon.zip
          retention-days: 7